CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(45) NOT NULL,
    firstname VARCHAR(45) NOT NULL,
    lastname VARCHAR(45) NOT NULL,
    password VARCHAR(45) NOT NULL,
    mobile VARCHAR(12) NOT NULL,
    roleId INTEGER NOT NULL,
    FOREIGN KEY(roleId) REFERENCES role(id)
);

CREATE TABLE IF NOT EXISTS role (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS solcelle (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(45) NOT NULL,
    description VARCHAR(252),
    model VARCHAR(45) NOT NULL,
    built VARCHAR(45) NOT NULL,
    output INTEGER NOT NULL,
    typeId INTEGER NOT NULL,
    FOREIGN KEY(typeId) REFERENCES type(id)
);

CREATE TABLE IF NOT EXISTS solcelle_user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userId INTEGER NOT NULL,
    solcelleId INTEGER NOT NULL,
    date DATETIME NOT NULL,
    FOREIGN KEY(userId) REFERENCES user(id),
    FOREIGN KEY(solcelleId) REFERENCES solcelle(id)
);

CREATE TABLE IF NOT EXISTS type (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(45) NOT NULL,
    description VARCHAR(252) NOT NULL,
    imgURL VARCHAR(45)
)

DROP TABLE solcelle;

DROP TABLE type;